### ISSUE TITLE
Code recommendations for inclusion in HADES

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Characterization#1]
I see several issues with the code that I think should be fixed if we want to include this package in HADES:

### Code style / indentation

The code style and indentation seems rather arbitrary, making the code hard to read. See for example [here](https://github.com/OHDSI/Characterization/blob/5df69c298a1028d7ca7cfa43317c02185ee96bef/R/Database.R#L50). I recommend using `styler` and auto-code-indentation (ctrl-a, ctrl=i) everywhere.

Also, I'm pretty sure you don't need `return()` around `invisible()` (e.g. [here](https://github.com/OHDSI/Characterization/blob/5df69c298a1028d7ca7cfa43317c02185ee96bef/R/Database.R#L254))

### ParalllelLogger::logInfo

`ParalllelLogger::logInfo()` is equivalent to `message()`, so I recommend using that. Also, you don't need `paste0()`. For example, 

```r
ParallelLogger::logInfo(paste0("Running dechallenge rechallenge analysis ", i))
```

can be rewritten as

```r
message("Running dechallenge rechallenge analysis ", i)
```

### Non-specific tryCatch blocks

I noticed several non-specific `tryCatch` blocks like [here](https://github.com/OHDSI/Characterization/blob/5df69c298a1028d7ca7cfa43317c02185ee96bef/R/RunCharacterization.R#L180), where any error message from a complex function call is simply ignored. This is the exact opposite of the 'fail fast, fail hard philosophy', making it really hard to identify problems in the code. If there's a problem, we'd like to know about it (through an informative error message) so we can fix it. I strongly recommend using `tryCatch` as a last resort, and only around function calls to other people's packages where we know there are conditions under which that code throws an error that we are OK with.

### TidySelect 

Nowadays, when using dplyr's `select()`, `rename()`, or `relocate()`, you shoudn't use `.data$` anymore. Instead you should use quotes (to avoid warnings). It's annoying, I know.

### Standard extensions

For SQLite database files, maybe use '.sqlite' as extension? (instead of no extension, like [here](https://github.com/OHDSI/Characterization/blob/5df69c298a1028d7ca7cfa43317c02185ee96bef/R/Database.R#L36)). Similarly, Andromeda files are zip files, so maybe end their file names with '.zip'?

### Closing connections

Any connection we open should also be closed to not eat unnecessary server resources. [This connection](https://github.com/OHDSI/Characterization/blob/5df69c298a1028d7ca7cfa43317c02185ee96bef/R/Database.R#L46) does not get closed.

**Comment by jreps** [comment]
fixed I'm develop

**Comment by schuemie** [comment]
(I made some [minor changes](https://github.com/OHDSI/Characterization/commit/fd927c2141c5f64f64bbb84cb4bac20a14963fcf) in develop, I hope that is ok.)

Thanks for those changes. I see the big tryCatch blocks are still there. Could you help me understand the thinking here? I always prefer for errors to be fatal, so we know we must fix them before proceeding. 

Imagine the following scenario: we run Characterization at a remote site with a weird database server. The server throws some error on one of the queries. However, the sys admin running the study thinks everything went well (the script completed thanks to the tryCatch block), and returns the results. We see no results, and think that particular outcome does not occur at the site, not knowing that it is a server error. 

Wouldn't it be better if the script just threw an error and stopped? Under what circumstances would we be ok with errors?

**Comment by jreps** [comment]
The try catches are there for the big run when you want hundreds of characterizations analyses being run.  If one fails for some odd reasons, it try's to run the 99 remaining rather than fail for all 100.  It's the same logic I use for PLP when the user wants to fit lots of models, if one errors, the others will still try to be fit.  The reason is that often when I press execute on a large study, I don't watch it, I leave it for a couple of hours and then check it.  I found it really annoying when one thing like an empty cohort or badly designed prediction stopped all the models, so I personally prefer the thing that are problematic get tried but do not break things for the other analyses.

That being said, the tryCatches should be recording the error message, so you can see what the issue was with the problematic analysis.  I thought I replaced the NULLs with printed messages but I must have forgotten.  I will edit those (although the issues may be printed inside the functions somewhere - so I will check that to make sure it's not redundant).  I think there is also a basic tracker I added, it needs to be improved, but it tells you what was run.

**Comment by schuemie** [comment]
Ok, I guess there's no right or wrong here.

If you could create a new release with the changes I just pushed to develop I think we're good to go for HADES.

**Comment by schuemie** [comment]
I made some more minor changes in develop (sorry, accidentally applied auto-indentation to Database.R). Once released I'll add this package to HADES.
